version: '3.8'
services:
  dev-db:
    image: postgres:13
    networks:
      - freecodecamp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  test-db:
    image: postgres:13
    networks:
      - freecodecamp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
networks:
  freecodecamp:
